# Generated by Django 4.0.3 on 2022-04-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
