# Generated by Django 4.0.3 on 2022-04-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0003_subdivision_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_created',
        ),
    ]
