# Generated by Django 4.0.3 on 2022-04-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0004_remove_user_user_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photographer', models.CharField(max_length=150)),
                ('source', models.URLField()),
                ('picture_url', models.URLField()),
                ('compress_url', models.URLField()),
                ('category', models.CharField(max_length=150)),
            ],
        ),
    ]
