# Generated by Django 4.0.4 on 2022-05-16 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0006_alter_user_photo_project_mindmap_kanbanboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
