# Generated by Django 4.0.4 on 2022-06-17 14:47

import django.core.validators
from django.db import migrations, models
import rt_app.common.services
import rt_app.projects.services
import rt_app.storages


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0009_user_banner_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(null=True, storage=rt_app.storages.OverwriteStorage, upload_to=rt_app.projects.services.get_path_to_picture, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg']), rt_app.common.services.validate_size_image]),
        ),
    ]
