# Generated by Django 4.0.4 on 2022-06-22 12:46

import django.core.validators
from django.db import migrations, models
import image_compressor.storages
import rt_app.projects.documents.services


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0010_alter_project_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Background',
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, storage=image_compressor.storages.OverwriteStorage, upload_to=rt_app.projects.documents.services.get_path_to_document, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx'])]),
        ),
    ]
