# Generated by Django 4.0.4 on 2022-06-22 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0013_mindcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindcard',
            name='mind_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rt_app.mindmap'),
        ),
        migrations.AlterField(
            model_name='mindcard',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target', to='rt_app.mindcard'),
        ),
    ]
