# Generated by Django 4.0.4 on 2022-06-23 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0014_alter_mindcard_mind_map_alter_mindcard_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kanban_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rt_app.kanbanboard')),
            ],
        ),
        migrations.CreateModel(
            name='KanbanCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('L', 'low'), ('A', 'average'), ('H', 'high')], max_length=1)),
                ('description', models.TextField(null=True)),
                ('kanban_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rt_app.kanbancolumn')),
            ],
        ),
    ]
