# Generated by Django 4.0.4 on 2022-06-24 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0016_remove_mindcard_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MindEdges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField()),
                ('mind_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rt_app.mindmap')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rt_app.mindcard')),
            ],
        ),
    ]
