# Generated by Django 4.0.4 on 2022-06-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0017_mindedges'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbancolumn',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
