# Generated by Django 4.0.4 on 2022-06-26 17:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import image_compressor.storages
import rt_app.common.services
import rt_app.users.services


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0018_kanbancolumn_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindedges',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rt_app.mindcard'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, storage=image_compressor.storages.OverwriteStorage, upload_to=rt_app.users.services.get_path_to_photo, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['JPG']), rt_app.common.services.validate_size_image]),
        ),
    ]
