# Generated by Django 3.2.10 on 2021-12-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
