# Generated by Django 3.2.10 on 2021-12-18 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0002_alter_customuser_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rightforspecialty',
            name='right',
        ),
        migrations.RemoveField(
            model_name='rightforspecialty',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='right',
        ),
        migrations.DeleteModel(
            name='Right',
        ),
        migrations.DeleteModel(
            name='RightForSpecialty',
        ),
    ]
