# Generated by Django 3.2.10 on 2021-12-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0003_auto_20211218_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
